version: 2.1

jobs: # a basic unit of work in a run
  mac: # your job name
    macos:
      xcode: 14.2.0 # indicate your selected version of Xcode
    resource_class: macos.m1.large.gen1
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
    
      - run: |
          # Install R
          wget https://cran.r-project.org/bin/macosx/base/R-4.2.3.pkg
          sudo installer -pkg R-4.2.3.pkg -target /
          export R_HOME=`R RHOME`
          # Install Julia
          
  linux: 
    working_directory: /root/project/DataCurator.jl   # Clone into a directory whose name matches your Package.
    docker:
      - image: julia:1.8
    steps: 
      - checkout
      - run: pwd
      - run: ls -alsht
          
  
# build:
#     working_directory: /root/project/DataCurator.jl   # Clone into a directory whose name matches your Package.
#     docker:
#       - image: julia:1.8
#     steps:
#       - run: pwd
#       - run: ls -alsht
#       - run: apt update
#       - run: apt install python3 -y
#       - run: apt install python3-pip -y
#       - run: pip3 install smlmvis
#       - run: pip3 install meshio
# #   build: 
#     macos:
#       xcode: 14.2.0 # indicate your selected version of Xcode
#     steps: 
#       - checkout
#       - run:
#          # build our application
#          name: Build Application
#          command: echo "Hi"

          
workflows:
  test_build:
    jobs:
      - mac
      - linux:
          requires:
            - mac
